
const arrLangText = {
    uk:{
        'title': 'Реєстрація',
        'choiseSex': 'Оберіть стать',
        'male': 'Чоловік',
        'female': 'Жінка',
        "choise": 'Виберіть рівень активності',
        'none': 'Малорухливий спосіб життя',
        'low': 'Мала активність (1-3 тренування на тиждень)',
        'middle': 'Середня активність (3-5 тренувань на тиждень)',
        'higth': 'Висока активність (5-7 тренувань на тиждень)',
        'veryHight': 'Дуже висока активність',
        "SingUp": 'Зареєструватися',
        "haveAcc": 'Вже маєте акаунт?',
        "login": 'Вхід',
        "logins": 'Логін',
        'calculate': 'Розрахувати',
        'headerEnter': 'Вхід',
        'headerSingUp': 'Реєстрація',
        'kg': 'Кг',
        'pound': 'Фунтів',
        'sm': 'См',
        'inches': 'Дюймів',
        'forGetPass': 'Забули пароль?',
        'havntAcc': 'Не маєте акаунту?',
        'regist': 'Зареєструватися',
        'lastWeight': 'Останнє зважування',
        'perfectWeight': 'Ідеальна вага',
        'wantWeight': 'Бажана вага',
        'activ': 'Рівень активності',
        'dataRegistr': 'Дата реєстрації',
        'wantDay': 'Бажана дата схуднення',
        'age': 'Вік',
        'sex' : 'Стать',
        'height': 'Зріст',
        'weight' : 'Вага',
        'changeBtn': 'Змінити',
        'oldYears': 'роки(ів)',
    },
    en:{
        'title': 'Sing Up',
        'choiseSex': 'Select gender',
        'male': 'Male',
        'female': 'Female',
        "choise": 'Choose an activity level',
        'none': 'Sedentary lifestyle',
        'low': 'Low activity (1-3 workouts per week)',
        'middle': 'Moderate activity (3-5 training sessions per week)',
        'higth': 'High activity (5-7 training sessions per week)',
        'veryHight': 'Very high activity',
        "SingUp": 'Sign Up',
        "haveAcc": 'Already have an account?',
        "login": 'Log In',
        "logins": 'Login',
        'calculate': 'Calculate',
        'headerEnter': 'Sign In',
        'headerSingUp': 'Sign Up',
        'kg': 'Kg',
        'pound': 'Pound',
        'sm': 'Sm',
        'inches': 'Inches',
        'forGetPass': 'Forgot your password?',
        'havntAcc': `Don't have an account?`,
        'regist': 'Sing Up',
        'lastWeight': 'Last weighing',
        'perfectWeight': 'Perfect weight',
        'wantWeight': 'Want weight',
        'activ': 'Activity level',
        'dataRegistr': 'Date of registration',
        'wantDay': 'Desired date to lose weight',
        'age': 'Age',
        'sex' : 'Sex',
        'height': 'Height',
        'weight' : 'Weight',
        'changeBtn': 'Change',
        'oldYears': 'years old',
    }
}
const arrLangPlaceholder = {
    'uk':{
        'login': 'Логін',
        'password': 'Пароль',
        'repeatPassword': "Повторіть пароль",
        'name': "Ім'я",
        'surname': "Прізвище",
        'age': "Вік",
        'height': "Зріст",
        'weight': "Вага",
        'wantDay': 'Кількість днів до цілі',
        'wantWeight': 'Важана вага',
    },
    'en':{
        'login': 'Login',
        'password': 'Password',
        'repeatPassword': "Repeat password",
        'name': "Name",
        'surname': "Surname",
        'age': "Age",
        'height': "Height",
        'weight': "Weight",
        'wantDay': 'Number of desired days',
        'wantWeight': 'Desired weight',
    },
}
const callArrLangPlaceholder= (count)=>{
    let arr = {}
count == 0 ? arr = arrLangPlaceholder.uk : arr = arrLangPlaceholder.en
return arr
}


const arrLangValidate = {
    'uk': {
        'login': 'Логін має бути більше 6 символів та не має містити жодних спеціальних символів (!@#$%^&*?/,.)',
        'password': 'Мінімум 8 символів, велика буква та цифра',
        'repeatPassword': "Паролі повинні повторюватись",
        'name': "Некоректне ім'я",
        'surname': "Некоректне прізвище",
        'age': "У такому віці краще зверніться до лікаря",
        'sex': 'Оберіть стать',
        'height': "З таким зростом краще зверніться до лікаря",
        'weight': "З такою вагою краще зверніться до лікаря",
        'activ': 'Оберіть рівень активності',
    },
    'en': {
        'login': 'The login must be longer than 6 characters and must not contain any special characters (!@#$%^&*?/,.)',
        'password': 'Minimum of 8 characters, uppercase letter and number',
        'repeatPassword': "Passwords must be the same",
        'name': "Invalid name",
        'surname': "Incorrect last name",
        'age': "At this age, it is better to consult a doctor",
        'sex': 'Select gender',
        'height': "With such growth, it is better to consult a doctor",
        'weight': "With such a weight, it is better to consult a doctor",
        'activ': 'Choose an activity level',
    }
}

export {arrLangText, arrLangPlaceholder, arrLangValidate, callArrLangPlaceholder}