
const arrLangText = {
    uk:{
        'title': 'Реєстрація',
        'choiseSex': 'Оберіть стать',
        'male': 'Чоловік',
        'female': 'Жінка',
        "choise": 'Оберіть рівень активності',
        'none': 'Малорухливий спосіб життя',
        'low': 'Мала активність (1-3 тренування на тиждень)',
        'middle': 'Середня активність (3-5 тренувань на тиждень)',
        'higth': 'Висока активність (5-7 тренувань на тиждень)',
        'veryHight': 'Дуже висока активність',
        "SingUp": 'Зареєструватися',
        "haveAcc": 'Вже маєте акаунт?',
        "login": 'Вхід',
        "logins": 'Логін',
        'calculate': 'Розрахувати',
        'headerEnter': 'Вхід',
        'headerSingUp': 'Реєстрація',
        'kg': 'Кг',
        'pound': 'Фунт(и/ів)',
        'poundParam': 'Фунти',
        'sm': 'См',
        'inches': 'Дюймів',
        'forGetPass': 'Забули пароль?',
        'havntAcc': 'Не маєте акаунту?',
        'regist': 'Зареєструватися',
        'lastWeight': 'Останнє зважування',
        'perfectWeight': 'Ідеальна вага',
        'wantWeight': 'Бажана вага',
        'activ': 'Рівень активності',
        'dataRegistr': 'Дата реєстрації',
        'wantDay': 'Бажана дата схуднення',
        'age': 'Вік',
        'sex' : 'Стать',
        'height': 'Зріст',
        'weight' : 'Вага',
        'changeBtn': 'Змінити',
        'oldYears': 'роки(ів)',
        'massageLink': 'для слідкуванням за своїм прогресом',
        'registerLink': 'Зареєструйтесь',
        'trueSignUp':'Реєстрація пройшла успішно!',
        "loginValidate": 'Має бути більше 6 символів та без спеціальних символів (!@#$...)',
        'passwordValidate': 'Мінімум 8 символів, велика буква та цифра',
        'password': 'Пароль',
        'repeatPasswordValidate': "Паролі повинні повторюватись",
        'repeatPassword': "Повторіть пароль",
        'nameValidate': "Некоректне ім'я",
        'nameSurmaneValidation': `Некоректне ім'я або прізвище`,
        'name': "Ім'я",
        'surnameValidate': "Некоректне прізвище",
        'ageValidate': "Некоректний вік",
        'sexValidate': 'Оберіть стать',
        'heightValidate': "Некоректний зріст",
        'weightValidate': "Некоректна вага",
        'activValidate': 'Оберіть рівень активності',
        'enterLoginValidate': 'Введіть логін',
        'enterPassValidate': 'Введіть пароль',
        'surname': "Прізвище",
        'emailValidate': 'Некоректний email',
        'email': 'Email',
        'incorectLogin': 'Логін або пароль невірний',
        'haveUser': 'Такий користувач вже існує',
        'wantDayValidate': 'Некоректна кількість днів',
        'wantDayNumber': 'Кількість днів до цілі',
        'requiredField' : `Обов'язкове поле`,
        'dateValidation': 'Не вірний формат (ДД/ММ/РР)',
        'Prev': 'Назад',
        'Next': 'Далі',
        //chart
        'extraCalories': 'Додаткові калорії',
        'remainderCalories': 'Зайві калорії',
        'yourCalorieCount': 'Ваша кількість калорій',
        'totalCalories': 'Загальна кількість калорій',
        'Calculate': 'Розрахувати',
        'CalculatingCalories': 'Розрахунок калорій',
        'PercentageOfFat': 'Процент жиру, %',
        'PercentageOfBodyFat': 'Процент жиру в організмі',
        'PerfectWeight': 'Ідеальна вага',
        'YourWeight': 'Ваша вага',
        'ToThePerfectWeight': 'До ідеальної ваги',
        'YourPerfectWeight': 'Ваша ідеальна вага',
        'YourWeightProgress': 'Прогрес вашої ваги',
        'Proteins': 'Білків',
        'Fats': 'Жирів',
        'Carbohydrates': 'Вуглеводів',
        'NumberCalories': 'Кількість калорій у білках, жирах та вугливодах',
        'BodyMassIndex': 'Індекс маси тіла',
        'ConsultDoctor': 'Звернітся до лікаря!',
        'save': 'Зберегти',
        'SignOut': 'Вихід',
        'AddedCalories': 'Додано Калорій',
        'DailyCaloric': 'Добова норма калорій',
        'DailyProtein': "Добова норма білків, жирів та вуглеводів",
        'TotalCalories': 'Калорій',
        'EnterNumber': 'Введіть число',
        'grams': 'грамів',

        'RemnantProteins': 'Залишок білків',
        'RemnantFats': 'Залишок жирів',
        'RemnantCarb': 'Залишок вуглеводів',

        'AddedProteins': 'Додано білків',
        'AddedFats': 'Додано жирів',
        'AddedCarb': 'Додано вуглеводів',

        'saveChange': 'Зберегти зміни',
        'leavePAge': 'На головну',
        //food
        'AllTypes': 'Всі типи їжі',
        'Alcohol': 'Алкогольні напої',
        'SoftDrinks': 'Безалкогольні напої',
        'Meat': `М'ясні продукти`,
        'Fish': 'Риба',
        'Sausage': 'Ковбасні вироби',
        'Vegetables': 'Овочі',
        'Fruits': 'Фрукти',
        'Porridge': 'Каші',
        'Mashrooms': 'Гриби',
        'Eggs': 'Яйця',
        'Nuts': 'Горіхи',
        'Milk': 'Молочні вироби',
        'Оil': 'Олія',
        'Sweets': 'Солодощі',
        'Bread': 'Хлібні вироби',
        'Selected': 'Обрані продукти',
        'Find': 'Знайди продукт',
        'error': 'Щось пішло не так',


        //food sort
        'sortBy': 'Сортування за',
        'textFromStart': 'назвою А-Я',
        'textFromEnd': 'назвою Я-А',
        'caloriesFromStart': 'зростанням калорій',
        'caloriesFromEnd': 'зменшенням калорій',
        'fatsFromStart':'зростанням жирів',
        'fatsFromEnd': 'зменшенням жирів',
        'proteinFromStart': 'зростанням білків',
        'proteinFromEnd': 'зменшенням білків',
        'carbFromStart': 'зростанням вуглеводів',
        'carbFromEnd': 'зменшенням вуглеводів',

    },
    en:{
        'title': 'Sing Up',
        'choiseSex': 'Select gender',
        'male': 'Male',
        'female': 'Female',
        "choise": 'Choose an activity level',
        'none': 'Sedentary lifestyle',
        'low': 'Low activity (1-3 workouts per week)',
        'middle': 'Moderate activity (3-5 training sessions per week)',
        'higth': 'High activity (5-7 training sessions per week)',
        'veryHight': 'Very high activity',
        "SingUp": 'Sign Up',
        "haveAcc": 'Already have an account?',
        "login": 'Log In',
        "logins": 'Login',
        'calculate': 'Calculate',
        'headerEnter': 'Sign In',
        'headerSingUp': 'Sign Up',
        'kg': 'Kg',
        'pound': 'Pounds',
        'poundParam': 'Pounds',
        'sm': 'Sm',
        'inches': 'Inches',
        'forGetPass': 'Forgot your password?',
        'havntAcc': `Don't have an account?`,
        'regist': 'Sing Up',
        'lastWeight': 'Last weighing',
        'perfectWeight': 'Perfect weight',
        'wantWeight': 'Want weight',
        'activ': 'Activity level',
        'dataRegistr': 'Date of registration',
        'wantDay': 'Desired date to lose weight',
        'age': 'Age',
        'sex' : 'Sex',
        'height': 'Height',
        'weight' : 'Weight',
        'changeBtn': 'Change',
        'oldYears': 'years old',
        'massageLink': 'to track your progress',
        'registerLink': 'Sign up',
        'trueSignUp':'Registration is successful',
        'loginValidate': 'The login must be longer than 6 characters and must not contain any special characters (!@#$%^&*?/,.)',
        'passwordValidate': 'Minimum of 8 characters, uppercase letter and number',
        'password': 'Password',
        'repeatPasswordValidate': "Passwords must be the same",
        'repeatPassword': "Repeat password",
        'nameValidate': "Invalid name",
        'nameSurmaneValidation': 'Invalid name or surname',
        'name': "Name",
        'surnameValidate': "Incorrect last name",
        'ageValidate': "Incorrect age",
        'sexValidate': 'Select gender',
        'heightValidate': "Incorrect height",
        'weightValidate': "Incorrect weight",
        'activValidate': 'Choose an activity level',
        'enterLoginValidate': 'Enter your login',
        'enterPassValidate': 'Enter your password',
        'surname': "Surname",
        'emailValidate': 'Incorrect email',
        'email': 'Email',
        'wantDayValidate': 'Incorrect number of days',
        'incorectLogin': 'The login or password is incorrect',
        'haveUser': 'This username already exists',
        'wantDayNumber': 'Number of desired days',
        'requiredField' : `Required field`,
        'dateValidation': 'Invalid format (DD/MM/YY)',
        'Prev': 'Prev',
        'Next': 'Next',
        //charts
        'extraCalories': 'Extra Calories',
        'remainderCalories': 'Extra Calories',
        'yourCalorieCount': 'Your Calorie Count',
        'totalCalories': 'Total Calories',
        'Calculate': 'Calculate',
        'CalculatingCalories': 'Calculating Calories',
        'PercentageOfFat': 'Percentage of fat, %',
        'PercentageOfBodyFat': 'Percentage of body fat',
        'PerfectWeight': 'Perfect weight',
        'YourWeight': 'Your weight',
        'ToThePerfectWeight': 'To the perfect weight',
        'YourPerfectWeight': 'Your Perfect Weight',
        'YourWeightProgress': 'Your Weight Progress',
        'Proteins': 'Proteins',
        'Fats': 'Fats',
        'Carbohydrates': 'Carbohydrates',
        'NumberCalories': 'Number of calories in proteins, fats and carbohydrates',
        'BodyMassIndex': 'Body mass index',
        'ConsultDoctor': 'Consult a doctor!',
        'save': 'Save',
        'SignOut': 'Sign Out',
        'AddedCalories': 'Added calories',
        'DailyCaloric': 'Daily caloric intake',
        'DailyProtein': "Daily rate of proteins, fats and carbohydrates",
        'TotalCalories': 'Total calories',
        'EnterNumber': 'Enter a number',
        'grams': 'grams',

        //food
        'AllTypes': 'All types of food',
        'Alcohol': 'Alcohol',
        'SoftDrinks': 'Soft drinks',
        'Meat': 'Meat products',
        'Fish': 'Fish',
        'Sausage': 'Sausage products',
        'Vegetables': 'Vegetables',
        'Fruits': 'Fruits',
        'Porridge': 'Porridge',
        'Mashrooms': 'Mashrooms',
        'Eggs': 'Eggs',
        'Nuts': 'Nuts',
        'Milk': 'Milk products',
        'Оil': 'Оil',
        'Sweets': 'Sweets',
        'Bread': 'Bread products',
        'Selected': 'Selected products',
        'Find': 'Find a product',

        'RemnantProteins': 'Remnant proteins',
        'RemnantFats': 'Remnant fats',
        'RemnantCarb': 'Remnant carb',

        'AddedProteins': 'Added proteins',
        'AddedFats': 'Added fats',
        'AddedCarb': 'Added carb',

        'saveChange': 'Save changes',
        'leavePAge': 'To Main',

        'error': 'Something went wrong',

        //food sort
        'sortBy': 'Sort by',
        'textFromStart': 'name А-Z',
        'textFromEnd': 'name Z-А',
        'caloriesFromStart': 'calories: highest first',
        'caloriesFromEnd': 'calories: lowest first',
        'fatsFromStart':'fats: highest first',
        'fatsFromEnd': 'fats: lowest first',
        'proteinFromStart': 'proteins: highest first',
        'proteinFromEnd': 'proteins: lowest first',
        'carbFromStart': 'carbohydrates: highest first',
        'carbFromEnd': 'carbohydrates: lowest first',
    }
}
const arrLangPlaceholder = {
    'uk':{
        'login': 'Логін',
        'password': 'Пароль',
        'repeatPassword': "Повторіть пароль",
        'name': "Ім'я",
        'surname': "Прізвище",
        'age': "Вік",
        'height': "Зріст",
        'weight': "Вага",
        'wantDay': 'Кількість днів до цілі',
        'wantWeight': 'Бажана вага',
        'email': 'Email',
    },
    'en':{
        'login': 'Login',
        'password': 'Password',
        'repeatPassword': "Repeat password",
        'name': "Name",
        'surname': "Surname",
        'age': "Age",
        'height': "Height",
        'weight': "Weight",
        'wantDay': 'Number of desired days',
        'wantWeight': 'Desired weight',
        'email': 'Email',
    },
}

const arrLangValidate = {
    'uk': {
        'login': 'Логін має бути більше 6 символів та не має містити жодних спеціальних символів (!@#$%^&*?/,.)',
        'password': 'Мінімум 8 символів, велика буква та цифра',
        'repeatPassword': "Паролі повинні повторюватись",
        'name': "Некоректне ім'я",
        'surname': "Некоректне прізвище",
        'age': "Некоректний вік",
        'sex': 'Оберіть стать',
        'height': "Некоректний зріст",
        'weight': "Некоректна вага",
        'activ': 'Оберіть рівень активності',
        'enterLogin': 'Введіть логін',
        'enterPass': 'Введіть пароль',
        'emailValidate': 'Некоректний email',
        'wantDay': 'Некоректна кількість днів'
    },
    'en': {
        'login': 'The login must be longer than 6 characters and must not contain any special characters (!@#$%^&*?/,.)',
        'password': 'Minimum of 8 characters, uppercase letter and number',
        'repeatPassword': "Passwords must be the same",
        'name': "Invalid name",
        'surname': "Incorrect last name",
        'age': "Incorrect age",
        'sex': 'Select gender',
        'height': "Incorrect height",
        'weight': "Incorrect weight",
        'activ': 'Choose an activity level',
        'enterLogin': 'Enter your login',
        'enterPass': 'Enter your password',
        'emailValidate': 'Incorrect email',
        'wantDay':'Incorrect number of days',
    }
}

export {arrLangText, arrLangPlaceholder, arrLangValidate}